version: '2'

services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD:
        ports:
            - "3306:3306"

    web:
        restart: always
        build: ./ciclocelular
        ports:
            - "8000"
        depends_on:
            - db
        volumes:
            - ./ciclocelular:/usr/src/app
        env_file: .env
        environment:
            DEBUG: 'true'
        command: /usr/local/bin/gunicorn ciclocelular.wsgi:application -w 2 -b :8000

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - /www/static
        volumes_from:
            - web
        links:
            - web:web
volumes:
    db_data:
